### ISSUE TITLE
fix: dropping files on Dock icon does not open them

### ISSUE THREAD

**Issue by brianjgoodwin** [brianjgoodwin/Jot#98]
## Summary

Dragging a supported file (.txt, .md) onto the Jot app icon in the Dock does not open the file. No error or console output is produced. File > Open works correctly for the same file types.

## Expected behavior

Dropping a supported file on the Dock icon should open it in a new editor window, consistent with standard macOS document app behavior.

## Context

- App is sandboxed with com.apple.security.files.user-selected.read-write
- NSDocumentController should handle Dock drops automatically for NSDocument-based apps
- Document types are declared in Info.plist (public.plain-text, net.daringfireball.markdown, public.source-code)
- AppDelegate does not implement application(_:open:) or application(_:openFile:) -- may need one of these
- Pre-existing issue, not a regression from #47

## Possible causes

- Missing application(_:open:) in AppDelegate
- LSItemContentTypes not matching what Finder sends for the dropped file
- Sandbox entitlement issue with Dock drops vs. user-selected files

## Related

- #47 (drag and drop onto editor window -- fixed)

**Comment by brianjgoodwin** [comment]
Investigated on `develop` (post-1.0.9): **cannot reproduce**. Opening files through the same LaunchServices `odoc` event a Dock drop sends (`open -a Jot file.txt` / `.md`) works in both cases:

- **App not running**: launches and opens the file in a document window
- **App already running**: opens a new document window, ordered front

The bug was real in older builds, though. Testing a stale pre-rewrite build reproduced the reported symptom exactly, in two forms:

1. **Launch via drop**: the app launches, state restoration runs, but the dropped file never becomes a document at all — no window, no error.
2. **Drop on a running app**: the document and its window are created (the file even lands in Recent Documents), but the window is never ordered front — calling `orderFrontRegardless` on it via lldb made it appear.

So the fix landed somewhere in the document-lifecycle work (most plausibly the #121/#118 overhaul in 1.0.9).

One environmental note from the investigation: LaunchServices on this machine has **40+ registered copies** of `com.brian.jot` (old DerivedData builds, archives, Desktop test copies, Downloads, iCloud Drive, Messages attachments). Worth cleaning up — deleting stale copies and running `lsregister -gc` — so drops and default-handler resolution reliably hit the intended copy.

Needs a hands-on confirmation: drag a .txt and a .md onto the Dock icon of the current build, both with the app closed and running. If both open, this can close as fixed in 1.0.9.

**Comment by brianjgoodwin** [comment]
Verified fixed in current builds — Dock drops open supported files as expected (likely resolved by the UTType constant migration in #197/#203 or an OS-side change; the original repro no longer occurs). Closing as verified-working; reopen with a repro if it recurs.
